### ISSUE TITLE
Contact Us button is not responsive

### ISSUE THREAD

**Issue by iamsnehadas** [Satakshijain/Coding-Hustlers#5]
The Contact Us button on the top of the page is not responsive.
![Screenshot (820)](https://user-images.githubusercontent.com/95439390/197038198-f60bf527-7e7b-48de-b12a-f51814197511.png)

**Comment by Satakshijain** [comment]
Hi @iamsnehadas I have assigned this issue to you can make it responsive

**Comment by iamsnehadas** [comment]
Hello, I have made it responsive. Please check. Thanks.
